# Autograd: Tự động tính đạo hàm

+ [LINK PYtorch tutorial](https://phamdinhkhanh.github.io/2019/08/10/PytorchTurtorial1.html)
+ Mặc định của requires_grad khi khởi tạo 1 tensor torch là False tức là sẽ không ghi lại lịch sử thay đổi.
+ requires_grad: save information gradient or not
+ grad_fn: save information about used function of tensor
+ backward() - compute derivative of function
+ grad - save derivative information 

In [2]:
# Mặc định của requires_grad khi khởi tạo 1 tensor torch là False tức là sẽ không ghi lại lịch sử thay đổi.
import torch

x = torch.ones(2, 2, requires_grad = True)
print(x)

y = x+2
print(y)

/home/tuandinh/Desktop/AI ML/Pytorch/env/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [3]:
print(y.grad_fn)

In [4]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [5]:
a = torch.ones(3, 3)
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b)
print(b.grad_fn)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
False
True
tensor(9., grad_fn=<SumBackward0>)


In [ ]:
#  thực hiện một lan truyền ngược (backprop) thông qua hàm out.backward()
out.backward()

In [10]:
# ket qua cua backprop duoc luu trong phan tu x.grad 
print(x.grad)


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [11]:
# torch.autograd sẽ là hàm chức năng tính tích giữa vector và ma trận jacobian. 
# Hàm số cho ta biết mức độ thay đổi của các chiều khi đi theo phương gradient.
import torch

x = torch.randn(3, requires_grad = True)
yhat = torch.randn(3, requires_grad = True)*2
y = x*2
l = ((y-yhat)**2).mean()
print(l)

tensor(6.8436, grad_fn=<MeanBackward0>)


+ Hàm torch.autograd sẽ không tính toán ma trận jacobian trực tiếp mà thay vào đó sẽ tính tích vector-jacobian theo vector truyền vào đối số .backward()

In [13]:
l.backward()

In [14]:
x.grad

tensor([-4.5874, -1.7472, -3.5218])

/tmp/ipykernel_6348/486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:480.)
  y.grad
