In [2]:
import torch
import numpy as np
x = torch.empty(5,3)
x

tensor([[-9.1788e+11,  3.0941e-41,  1.4013e-45],
        [ 0.0000e+00, -9.1786e+11,  3.0941e-41],
        [-9.1786e+11,  3.0941e-41,  3.3631e-44],
        [ 4.5887e-41,  3.6010e+25,  4.5887e-41],
        [ 2.8026e-45,  9.8091e-45,  2.8026e-45]])

In [3]:
# matrix nau nhien
torch.rand(5,3)

tensor([[0.5486, 0.2260, 0.3638],
        [0.3347, 0.7156, 0.7925],
        [0.0025, 0.2452, 0.1512],
        [0.3953, 0.1101, 0.2680],
        [0.2054, 0.0494, 0.5496]])

In [5]:
# matrix 0 with type long
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
# khoi tao ma tran co kich thuoc tuong tu ma tran san co
x = x.new_ones(5,3,dtype=torch.double)
print(x.size())
x

torch.Size([5, 3])


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

# Operation with pytorch

In [9]:
x = torch.randn(5,3)
print(x)
y = torch.ones(5,3)
print(y)
print(x+y)

tensor([[ 0.8776,  0.5876, -0.1372],
        [ 0.9304,  1.0421, -0.7672],
        [-0.6128,  0.6739, -0.4762],
        [-0.5584, -0.7221,  0.2683],
        [-0.6018, -1.1810, -0.0672]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 1.8776,  1.5876,  0.8628],
        [ 1.9304,  2.0421,  0.2328],
        [ 0.3872,  1.6739,  0.5238],
        [ 0.4416,  0.2779,  1.2683],
        [ 0.3982, -0.1810,  0.9328]])


In [10]:
print(torch.add(x,y))

tensor([[ 1.8776,  1.5876,  0.8628],
        [ 1.9304,  2.0421,  0.2328],
        [ 0.3872,  1.6739,  0.5238],
        [ 0.4416,  0.2779,  1.2683],
        [ 0.3982, -0.1810,  0.9328]])


In [12]:
z = torch.empty(5,3)
torch.add(x,y,out=z)
z

tensor([[ 1.8776,  1.5876,  0.8628],
        [ 1.9304,  2.0421,  0.2328],
        [ 0.3872,  1.6739,  0.5238],
        [ 0.4416,  0.2779,  1.2683],
        [ 0.3982, -0.1810,  0.9328]])

In [13]:
print(x.add(y))
print(y.add(x))

tensor([[ 1.8776,  1.5876,  0.8628],
        [ 1.9304,  2.0421,  0.2328],
        [ 0.3872,  1.6739,  0.5238],
        [ 0.4416,  0.2779,  1.2683],
        [ 0.3982, -0.1810,  0.9328]])
tensor([[ 1.8776,  1.5876,  0.8628],
        [ 1.9304,  2.0421,  0.2328],
        [ 0.3872,  1.6739,  0.5238],
        [ 0.4416,  0.2779,  1.2683],
        [ 0.3982, -0.1810,  0.9328]])


In [15]:
# Truy cập index
# cot thu 2 cua x
print(x[:1])

tensor([[ 0.8776,  0.5876, -0.1372]])


In [17]:
# reshape tensor
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(y)
print(x.size(), y.size(), z.size())

tensor([ 0.4471,  0.3254,  1.1537,  1.8230, -1.2919,  1.6099, -1.3405, -0.9357,
         0.6332, -0.5359, -0.0235, -1.7471, -1.0080,  0.8631, -0.1161,  1.5770])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
# Chúng ta có thể chuyển tensor x có 1 phần tử sang 1 numeric python bằng hàm item().
x = torch.tensor([1.5])
i = x.item()
print(i)

1.5


# Connect with numpy

In [20]:
# chuyen doi tensor sang numpy
a = torch.ones(5,3)
print(type(a))
b = a.numpy()
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [22]:
#  b deu thay doi khi a thay doi. tuc ma tran numpy chuyen tu tensor sang co lien he voi nhau
a.add_(1)
print(a)
print(b)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [30]:
# Chuyển đổi numpy array sang torch tensor
a = np.array([1, 2, 3])
t = torch.from_numpy(a)
print(a)
print(t)
print(type(a))
print(type(t))

[1 2 3]
tensor([1, 2, 3])
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


# CUDA tensor

In [31]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))